[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "python-business-management-system"
version = "0.1.5"
description = "A Python-based business management system for sales, inventory, and invoicing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.setuptools.packages.find]
include = [
    "application*",
    "domain*",
    "infrastructure*",
    "presentation*"
]